# Generated by Django 4.2.2 on 2023-08-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
