# Generated by Django 4.2.2 on 2023-08-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_products_rating_alter_products_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='hotProducts',
            field=models.BooleanField(default=False),
        ),
    ]
